cm550_remocon_bridge_node:
  ros__parameters:
    port: '/dev/ttyACM0'
    baudrate: 57600
    serial_timeout_sec: 0.05
    write_delay_sec: 0.02
    resend_same_motion_command: true
    resend_same_aux_command: false

    command_topic: '/max/motion_cmd'
    page_topic: '/max/motion_page_cmd'
    status_topic: '/max/motion_status'
    last_page_topic: '/max/motion_last_page'
    command_map: 'walk:103,follow:103,stop:1,idle:1,turn_left:50,spin_left:50,turn_right:51,spin_right:51,reverse:158,stand:1,stand_up:3,sitdown:60,hello:5,clap:9'
    command_sequences: 'walk:101|103,follow:101|103,reverse:156|158'
    sequence_step_delay_sec: 0.8
    ignore_unknown_commands: true
    strip_action_metadata: true
    walk_repeat_count: 1

    head_raw_topic: '/max/head_cmd_raw'
    head_angle_topic: '/max/head_cmd'
    head_preset_topic: '/max/head_preset'
    head_status_topic: '/max/head_cmd_sent'
    center_raw: 512
    min_raw: 344
    max_raw: 680
    radians_per_range: 1.5708
    preset_map: 'center:512,left:680,right:344'

    led_preset_topic: '/max/led_preset'
    led_raw_topic: '/max/led_cmd_raw'
    led_status_topic: '/max/led_cmd_sent'
    led_preset_map: 'off:20000,red:20001,blue:20002,magenta:20003'
